/** @type {import('tailwindcss').Config} */
export default {
  content: ['./*.html', './src/**/*.{js,css}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e1e3e3',
        'surface-container': '#eceeee',
        'on-surface-variant': '#3d4a3e',
        'outline-variant': '#bbcbbb',
        'on-tertiary-container': '#8e0505',
        'on-primary-fixed-variant': '#005228',
        secondary: '#735c00',
        'on-primary-fixed': '#00210c',
        'secondary-fixed-dim': '#eec209',
        'secondary-fixed': '#ffe084',
        'on-background': '#191c1d',
        'surface-bright': '#f8fafa',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#574500',
        'primary-fixed': '#6bfe9c',
        'on-surface': '#191c1d',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-container': '#2ecc71',
        tertiary: '#b4271d',
        'surface-container-high': '#e6e8e9',
        'secondary-container': '#fed023',
        'surface-tint': '#006d37',
        'on-error': '#ffffff',
        'on-primary-container': '#005027',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#4ae183',
        'primary-fixed-dim': '#4ae183',
        'tertiary-container': '#ff9687',
        primary: '#006d37',
        surface: '#f8fafa',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#ffdad5',
        'on-tertiary-fixed-variant': '#910807',
        'tertiary-fixed-dim': '#ffb4a9',
        'surface-container-low': '#f2f4f4',
        'on-secondary-container': '#6f5900',
        background: '#f8fafa',
        'on-secondary-fixed': '#231b00',
        'on-tertiary-fixed': '#410000',
        'surface-container-highest': '#e1e3e3',
        'inverse-surface': '#2e3131',
        error: '#ba1a1a',
        outline: '#6c7b6d',
        'surface-dim': '#d8dada',
        'inverse-on-surface': '#eff1f1',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'stack-lg': '48px',
        'stack-sm': '12px',
        'container-max': '1200px',
        'margin-mobile': '20px',
        'stack-md': '24px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-xl': ['Manrope'],
        'headline-lg': ['Manrope'],
        'headline-lg-mobile': ['Manrope'],
        'body-md': ['Be Vietnam Pro'],
        'body-lg': ['Be Vietnam Pro'],
        'label-sm': ['Manrope'],
      },
      fontSize: {
        'label-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'headline-lg-mobile': [
          '28px',
          { lineHeight: '34px', fontWeight: '700' },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': [
          '40px',
          { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
      },
    },
  },
  plugins: [],
}
